appcode/__init__.py
import os
from flask import Flask

def create_app(test_config=None):
    # create and configure the app
    application = Flask(__name__, instance_relative_config=True)
    application.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(application.instance_path, 'flaskr.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        application.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        application.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(application.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @application.route('/')
    def hello():
        return '<p>Hello, AWS!</p><a href="/today">today link</a>'

    import appcode.routes.routes as routes
    application.register_blueprint(routes.bp)
   
    return application

application = create_app()

appcode/routes/routes.py
import functools
from flask import render_template, Blueprint, redirect
import yfinance as yf
import datetime
from appcode.routes.charts.chartFuncs import todayPlot, histPlot, barAnnual, lineDebt
import urllib.request, json
ticker = yf.Ticker('^GSPC')
import pandas as pd

# trying something...
import ssl

bp = Blueprint('routes', __name__, url_prefix='')

@bp.route('/today', methods=(['GET']))
def today():
    
    # Get raw data from yfinance
    raw = ticker.history(period="10y").Close.asfreq('D', method='bfill')
    d = raw/raw[0]

    # First chart...
    # Plot last 10 years of data from current date, e
    end = datetime.date.today() + datetime.timedelta(days=1)
    start = datetime.date.today() - datetime.timedelta(days=365*10)
    chart1 = todayPlot(d.asfreq('D'), annLow=False, annHigh=True, annGr=True)

    # Second chart...
    # find start date of current cycle (max value between ep, and e), reslice data, and re-normalize
    maxDate = raw.idxmax()
    chart2 = todayPlot(raw[maxDate:end] / raw[maxDate], annLow=True, annHigh=False, annGr=False)

    # get chart text and create list for template
    data = [chart1, chart2]

    return render_template('today.html', data=data)


@bp.route('/history', methods=(['GET']))
def history():
    # yFinance, get raw data
    raw = ticker.history(period="max")

    # call plot functions and pass to data aray
    data=[barAnnual(raw), histPlot(raw, growth=True, log=False), histPlot(raw, growth=True, log=True)]

    # pass data arraw for rendering, data needs to be .png file pointers
    return render_template('history.html', data=data)


@bp.route('/debt', methods=(['GET']))
def debt():
    ssl._create_default_https_context = ssl._create_unverified_context
    url = "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_outstanding?sort=-record_date&format=json&page[number]=1&page[size]=10000"
    response = urllib.request.urlopen(url)
    print(response.status)
    feddata = response.read()
    dict = json.loads(feddata)
    
    fiscal_year = []
    debt = []
    for d in dict["data"]:
        # print(type(float(d["debt_outstanding_amt"])), type(d["record_fiscal_year"]))
        debt.append(float(d["debt_outstanding_amt"]))
        fiscal_year.append(int(d["record_fiscal_year"]))
    
    debtData = pd.DataFrame({'year':fiscal_year, 'debt':debt})
    
    data = [ lineDebt(debtData) ]
    return render_template('debt.html', data=data)

appcode/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Otium</title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' media='screen' href={{ url_for('static', filename='style.css') }}>
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <div class="navbar justify-content-center">
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                    <a class="{{ 'nav-link active' if active_page=='today' else 'nav-link' }}" href="{{ url_for('routes.today') }}">Current Cycle</a>
                </li>
                <li class="nav-item">
                    <a class="{{ 'nav-link active' if active_page=='history' else 'nav-link' }}" href="{{ url_for('routes.history') }}">History</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="{{ 'nav-link active' if active_page=='debt' else 'nav-link' }}" href="{{ url_for('routes.debt') }}">Debt</a>
                </li> -->
            </ul>
        </div>
    </nav>
    <div class="container-fluid base-div">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

appcode/templates/debt.html
{% extends "base.html" %}
{% set active_page="debt" %}

{% block content %}

{% for d in data %}
    <div class="chart-frame">
        <div class="chart">
            <img src='data:image/png;base64,{{ d }}'/>
        </div>
    </div> 
{% endfor %}

{% endblock %}

appcode/templates/history.html
{% extends "base.html" %}
{% set active_page="history" %}

{% block content %}

{% for d in data %}
    <div class="chart-frame">
        <div class="chart">
            <img src='data:image/png;base64,{{ d }}'/>
        </div>
    </div> 
{% endfor %}

{% endblock %}

appcode/templates/today.html
{% extends "base.html" %}
{% set active_page="today" %}

{% block content %}

{% for d in data %}
    <div class="chart-frame">
        <div class="chart">
            <img src='data:image/png;base64,{{ d }}'/>
        </div>
    </div> 
{% endfor %}

{% endblock %}